### ISSUE TITLE
Backtest ValueError: NaN or Inf encountered!  symbol=600832.SH

### ISSUE THREAD

**Issue by maminzhao** [quantOS-org/JAQS#46]
Traceback (most recent call last):
  File "/home/ma/Documents/workspace-python/QuantSystem/JAQS/test/my_alpha_test.py", line 100, in <module>
    tr,props = do_back_test(dv)
  File "/home/ma/Documents/workspace-python/QuantSystem/JAQS/test/my_alpha_test.py", line 76, in do_back_test
    bt.run_alpha()
  File "/home/ma/Documents/workspace-python/QuantSystem/JAQS/jaqs/trade/backtest.py", line 454, in run_alpha
    self.re_balance_plan_after_open()
  File "/home/ma/Documents/workspace-python/QuantSystem/JAQS/jaqs/trade/backtest.py", line 408, in re_balance_plan_after_open
    suspensions=all_list)
  File "/home/ma/Documents/workspace-python/QuantSystem/JAQS/jaqs/trade/strategy.py", line 712, in generate_weights_order
    sec, price, w))
ValueError: NaN or Inf encountered! 
trade_date=20150520, symbol=600832.SH, price=nan, weight=0.0059713192234979486

600832这个股票在20150520退市了，这种情况没有处理么，只要遇到这种情况就会终止运行么？

**Comment by CKAtGitHub** [comment]
同问，不知道题主解决了吗？
