### ISSUE TITLE
装完jaqs后vnpy启动不了了

### ISSUE THREAD

**Issue by zjx** [quantOS-org/JAQS#7]
提示pandas版本冲突，需要重新编译。。jaqs和vnpy是不是需要某些特定的对应版本一致才能共同运行？

**Comment by zjx** [comment]
`
python run.py
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway, ibGateway, 
  File "/home/zjx/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/tkproGateway/__init__.py", line 4, in <module>
    from .tkproGateway import TkproGateway
  File "/home/zjx/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/tkproGateway/tkproGateway.py", line 19, in <module>
    from .DataApi import DataApi
  File "/home/zjx/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/tkproGateway/DataApi/__init__.py", line 10, in <module>
    from .data_api import DataApi
  File "/home/zjx/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/tkproGateway/DataApi/data_api.py", line 13, in <module>
    from . import utils
  File "/home/zjx/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/tkproGateway/DataApi/utils.py", line 9, in <module>
    import pandas    as pd
  File "/home/zjx/anaconda2/lib/python2.7/site-packages/pandas/__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: numpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
`

**Comment by brillliantz** [comment]
根据你的错误信息，应该是`pandas`包损坏，重装看是否能解决问题：
```python
pip uninstall pandas
pip install pandas
```
