### ISSUE TITLE
DoubleMA 的Backtest 执行后进行 analyze，出现KeyError: 'axes.titlepad is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.'

### ISSUE THREAD

**Issue by red7hj** [quantOS-org/JAQS#9]
Begin: DataApi login 13618*********@tcp://data.tushare.org:8910
    Already login as 13618*********, skip init_from_config
process trades...
get daily stats...
calc strategy return...
D:\python_Anaconda3\lib\site-packages\numpy\lib\function_base.py:3167: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
D:\python_Anaconda3\lib\site-packages\numpy\lib\function_base.py:3168: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
Traceback (most recent call last):
  File "D:\python_Anaconda3\lib\site-packages\matplotlib\__init__.py", line 880, in __setitem__
    cval = self.validate[key](val)
KeyError: 'axes.titlepad'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/JAQS-master/example/eventdriven/DoubleMA.py", line 230, in <module>
    analyze()
  File "D:/JAQS-master/example/eventdriven/DoubleMA.py", line 225, in analyze
    ta.do_analyze(result_dir=result_dir_path, selected_sec=[])
  File "D:\python_Anaconda3\lib\site-packages\jaqs\trade\analyze\analyze.py", line 506, in do_analyze
    self.plot_pnl(result_dir)
  File "D:\python_Anaconda3\lib\site-packages\jaqs\trade\analyze\analyze.py", line 400, in plot_pnl
    mpl.rcParams.update(MPL_RCPARAMS)
  File "D:\python_Anaconda3\lib\site-packages\matplotlib\__init__.py", line 914, in update
    self[k] = v
  File "D:\python_Anaconda3\lib\site-packages\matplotlib\__init__.py", line 886, in __setitem__
Plot strategy PnL...
    See rcParams.keys() for a list of valid parameters.' % (key,))
KeyError: 'axes.titlepad is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.'

Process finished with exit code 1

---------------------------------------------
执行过： pip install jaqs --upgrade  ，各个jaqs依赖的python的包应该都是最新版。
python3.5.2
windows系统。

**Comment by brillliantz** [comment]
谢谢你的反馈，这里代码是在设置`axes.titlepad`属性，以调整图片样式。我在matplotlib文档确认，当前稳定版本是有这个属性的，推荐您尝试`pip install --upgrade matplotlib`来升级后再尝试。另外，最新版Anaconda附带的matplotlib也是支持这个属性的
